[licenses]
allow = [
    "MIT",
    "Apache-2.0",
    "BSD-2-Clause",
    "Zlib",
    "Unicode-3.0",
    "CDLA-Permissive-2.0",
    "ISC",
    "BSD-3-Clause",
    "MPL-2.0",
]

[advisories.ignore]
["RUSTSEC-2025-0057"]