# Maximum line length
max_width = 120

# Tabs & indentation
hard_tabs = false
tab_spaces = 4

# Maximum width for struct literals before wrapping
struct_lit_width = 80

# Function parameters layout
fn_params_layout = "Vertical" # options: Compressed, Tall, Vertical

# Control import reordering (stable)
reorder_imports = true

# Control how single-line if/else blocks are formatted
single_line_if_else_max_width = 80
